### ISSUE TITLE
Error al iniciar el dominio de Glassfish

### ISSUE THREAD

**Issue by juligon** [rootbean/configuracion_portafolio_openshift#1]
Hola Ruber.
Segui paso por paso, y tengo un error cuando doy push obtengo un error: 
`line 8: ../../../bin/asadmin: Permission denied `

Entonces, lo mas lógico, ingrese al servidor por ssh y le di permisos 755 -R a la carpeta de glassfish. Luego intento ejecutar el dominio: `"asadmin start-domain domain1" `
y me sale el siguiente error: 
**`java.lang.IllegalStateException: java.net.UnknownHostException: OPENSHIFT_DIY_IP`** 

¿¿Me podria ayudar a solucionar el error ?? 
NOTA: No creo un pool de conexiones. copio la carpeta tal cual de su repo de github a mi repo de openshift. Muchas Gracias. 

Saludos desde CO.﻿
Juliang.

**Comment by rootbean** [comment]
Hola juligon,

1. Copia los archivos de https://drive.google.com/folderview?id=0B_ZidpDI-rAWT1o0bmJ5YndzazA&usp=sharing

2. Y si se debe editar el archivo domain.xml que se encuentra en domain1 en la carpeta del server. Para que con esto se logre comunicar con la bd.

Intenta con eso.. me comentas, y si gustas mañana acordamos y te ayudo a dar solución.

**Comment by juligon** [comment]
Hola Ruber.
Ya solucione el error. El problema era de permisos debido a que lo estaba ejecutando desde windows, los permisos no son iguales al sistema de linux. Entonces me cambie a mi ubuntu y le asigne permisos hice push y de inmediato funciono. 

Todos los archivos estan correctamente.

Saludos.
